# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  push:
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # - name: Check out the code
      #   uses: actions/checkout@v2
          # "justsecret='$(echo ${{ env.secret }})'" | Out-File -Append -FilePath $env:GITHUB_ENV

      - name: Create GitHub Variable
        id: set-vars
        run: |
          "data=Some Data" | Out-File -Encoding utf8 -Append -FilePath $env:GITHUB_ENV
          "secretdata='$((echo ""${{ secrets.JSON }}"" | ConvertFrom-Json).a)'" | Out-File -Encoding utf8 -Append -FilePath $env:GITHUB_ENV
          echo "::set-env name=envdata::'$((echo ${{ env.secret }} | ConvertFrom-Json).a)'"
        shell: pwsh
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
          

      - name: Echo env:data
        run: |
          Write-Output "Out: ${{ env.secretdata }}"
        shell: pwsh
