# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Write GITHUB_ENV
        run: |
          "data='Some Data'" | Out-File -FilePath $env:GITHUB_ENV
          "secretdata=$((ConvertFrom-Json '{""foo"": 0 }').foo)" | Out-File -FilePath $env:GITHUB_ENV
          "envsecret=$secret" | Out-File -FilePath $env:GITHUB_ENV
        shell: pwsh
        env:
          secret: ${{ secrets.JSON }}

      - name: Echo env:data
        run: |
          echo $data
          echo $envsecret
        shell: pwsh

