# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  push:
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

defaults:
  run:
    shell: pwsh

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    outputs:
      data: ${{ steps.setvars.outputs.data }}
      code: ${{ steps.setvars.outputs.code }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # - name: Check out the code
      #   uses: actions/checkout@v2

      - name: Create GitHub Variable
        id: setvars
        run: |
          $jsonData="{'prop1':'string prop', 'prop2':3}";
          "data=Some Data" | Out-File -Encoding utf8 -Append -FilePath $env:GITHUB_ENV
          "secretdata='$((echo ""${{ secrets.JSON }}"" | ConvertFrom-Json).a)'" | Out-File -Encoding utf8 -Append -FilePath $env:GITHUB_ENV
          echo "fromJSON: ${{ fromJSON(secrets.JSON).a }} "
          echo "::set-output name=data::Some Data"
          Write-Output "::set-output name=secret::'${{ secrets.JSON }}'"
          Write-Output "::set-output name=code::$((echo ""${{ secrets.JSON }}"" | ConvertFrom-Json).a)"

      - name: Echo env
        run: |
          Write-Output "Out: ${{ env.secretdata }}"
          Write-Output "Out: ${{ fromJSON(steps.setvars.outputs.secret).a }}"

      - name: Echo outputs
        run: |
          Write-Output "Data: ${{ steps.setvars.outputs.data }}"
          Write-Output "Secret: ${{ steps.setvars.outputs.secret }}"
          Write-Output "Code: ${{ steps.setvars.outputs.code }}"

  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    needs: build
    steps:
      - name: Show Output
        run: | 
          Write-Output "Data: ${{ needs.build.outputs.data }}"
          Write-Output "Code: ${{ needs.build.outputs.code }}"
